//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_BIBLIOTHEQUE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class admins
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public admins()
        {
            this.historique = new HashSet<historique>();
            this.inscription = new HashSet<inscription>();
        }
    
        public int id { get; set; }
        public string prenom_admin { get; set; }
        public string nom_admin { get; set; }
        public string adresse_admin { get; set; }
        public string tel_admin { get; set; }
        public string email_admin { get; set; }
        public Nullable<int> statut { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<int> delete { get; set; }
        public Nullable<int> type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historique> historique { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inscription> inscription { get; set; }
    }
}
