//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_BIBLIOTHEQUE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class historique
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_debut_cnx { get; set; }
        public Nullable<System.DateTime> date_fin_cnx { get; set; }
        public Nullable<int> admin_id { get; set; }
    
        public virtual admins admins { get; set; }
    }
}
