//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_BIBLIOTHEQUE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class livre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public livre()
        {
            this.pret = new HashSet<pret>();
        }
    
        public int id { get; set; }
        public string libelle_livre { get; set; }
        public string maison_edition { get; set; }
        public Nullable<int> qte_stock { get; set; }
        public Nullable<int> auteur_id { get; set; }
        public Nullable<int> categorie_id { get; set; }
        public Nullable<int> niveau_etude_id { get; set; }
        public Nullable<int> deletee { get; set; }
        public Nullable<int> qte_pret { get; set; }
    
        public virtual auteur auteur { get; set; }
        public virtual categorie categorie { get; set; }
        public virtual niveau_etude niveau_etude { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pret> pret { get; set; }
    }
}
