//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GESTION_BIBLIOTHEQUE.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bibliothequeEntities : DbContext
    {
        public bibliothequeEntities()
            : base("name=bibliothequeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admins> admins { get; set; }
        public virtual DbSet<auteur> auteur { get; set; }
        public virtual DbSet<categorie> categorie { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<historique> historique { get; set; }
        public virtual DbSet<inscription> inscription { get; set; }
        public virtual DbSet<livre> livre { get; set; }
        public virtual DbSet<niveau_etude> niveau_etude { get; set; }
        public virtual DbSet<pret> pret { get; set; }
    }
}
